[build-system]
requires = [
    "setuptools",
    "setuptools_scm"
]
build-backend = "setuptools.build_meta"

[project]
name = "fibonacci_friday_afternoon"
description = "a description"
dependencies = ["pandas", "numpy"]
dynamic = ["version"]
